name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        IMAGE_TAG="innei/shiro:1.2.5"
        docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Save the Docker image to a tar file
      run: |
        IMAGE_TAG="innei/shiro:1.2.5"
        docker save -o my-image-name.tar $IMAGE_TAG

    - name: Upload the Docker image as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: shiro-1.2.5.tar
